[variables]
NODE_VERSION = "22.12.0"

[phases.setup]
nixPkgs = ['nodejs_22']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'npx serve dist/highline-adventures-angular -s -n -l tcp://0.0.0.0:$PORT'